#!/usr/bin/env python2

import sys
import getopt
import os
import logging

from arkos.core.daemon import Daemon
from arkos.kraken.standalone import run_daemon


class KrakenDaemon(Daemon):
    def run(self):
        run_daemon(self.log_level, self.config_file)


def usage():
    print """
Usage: kraken [options]
Options:
    -c, --config <file> - Use given config file instead of default
    -v                  - Debug/verbose logging
    -d, --start         - Run in background (daemon mode)
    -r, --restart       - Restart daemon
    -s, --stop          - Stop daemon
    -h, --help          - This help
    """


if __name__ == '__main__':
    reload(sys)
    sys.setdefaultencoding('utf-8')
    sys.dont_write_bytecode = True

    log_level = logging.INFO
    config_file = ''

    try:
        opts, args = getopt.getopt(sys.argv[1:], 'hc:drsv', ['help', 'config=', 'start', 'stop', 'restart'])
    except getopt.GetoptError, e:
        print str(e)
        usage()
        sys.exit(2)

    action = 'run'
    os.environ['XTABLES_LIBDIR'] = '/usr/lib/iptables'

    for o, a in opts:
        if o in ('-h', '--help'):
            usage()
            sys.exit(0)
        elif o in ('-v',):
            log_level = logging.DEBUG
        elif o in ('-c', '--config'):
            if os.path.isfile(a):
                config_file = a
        elif o in ('-d', '--start'):
            action = 'start'
        elif o in ('-r', '--restart'):
            action = 'restart'
        elif o in ('-s', '--stop'):
            action = 'stop'

    # Find default config file
    if not config_file:
        # Check for config file in /etc/genesis/genesis.conf
        if os.path.isfile('/etc/arkos/settings.json'):
            config_file = '/etc/arkos/settings.json'
        elif os.path.isfile(os.path.join(sys.path[0], 'settings.json')):
            # Try local config file
            config_file = os.path.join(sys.path[0], 'settings.json')
    
    if action == 'run':
        run_daemon(log_level, config_file)
    else:
        krakend = KrakenDaemon('/var/run/kraken.pid', stdout='/var/log/kraken.log')
        krakend.log_level = log_level
        krakend.config_file = config_file

        if 'start' == action:
            krakend.start()
        elif 'stop' == action:
            krakend.stop()
        elif 'restart' == action:
            krakend.restart()
        else:
            usage()
            sys.exit(2)

    sys.exit(0)
